Use bundled inter font
next/font was fetching from Google Fonts at build time, which has timed
out. Persumably rate limiting?

    FetchError: request to https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap failed, reason:
        ...
        type: 'system',
        errno: 'ETIMEDOUT',
        code: 'ETIMEDOUT'
    }